environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
      configuration: Release

platform: Any CPU

before_build:
  - dotnet restore Amiga.sln --verbosity normal

build:
  parallel: true
  project: Amiga.sln

artifacts:
  - path: AmigaTools-Windows-x64.zip
    name: AmigaTools-Windows-x64
  - path: AmigaTools-Windows-x86.zip
    name: AmigaTools-Windows-x86
  - path: AmigaTools-Linux.tar.gz
    name: AmigaTools-Linux
  - path: AmigaTools-Mac-Arm.zip
    name: AmigaTools-Mac-Arm
  - path: AmigaTools-Mac-x64.zip
    name: AmigaTools-Mac-x64
  - path: nuget\*.nupkg
    name: NugetPackages

after_build:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { ./publish.ps1 }
    - ps: ./nuget.ps1

test: false

deploy:
  - provider: GitHub
    name: AmigaTools-Windows-x64
    artifact: AmigaTools-Windows-x64
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmigaTools-Windows-x86
    artifact: AmigaTools-Windows-x86
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmigaTools-Linux
    artifact: AmigaTools-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmigaTools-Mac-x64
    artifact: AmigaTools-Mac-x64
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmigaTools-Mac-Arm
    artifact: AmigaTools-Mac-Arm
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    name: NugetPackages
    api_key:
      secure: oL/d8rm+IPuxW+jM+Wse6Jydr38ctRcYj6Exot+ISFw4UGJbAoFeORwGQn7c8NQo
    skip_symbols: true
